"""Changed the repr functions

Revision ID: 9cbace057015
Revises: 3c86d230fcbe
Create Date: 2024-07-25 11:18:07.384498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbace057015'
down_revision = '3c86d230fcbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
